Windows build failure fix
Windows build was failing due to `error C3861: '_BitScanForward64':` and  `error C3861: '_BitScanReverse64':`. Simply changed them to `_BitScanForward` and `_BitScanReverse` on my x64 machine to make the Build successful