Remove executable bit from test scripts (#2734)
These are no all driven by only by the two top level scripts:

  check.py
  auto_update_tests.py

What is more all of them were broken when run isolation due to
relative import rules in python3.  e.g.:

```
$ scripts/test/binaryenjs.py
Traceback (most recent call last):
  File "scripts/test/binaryenjs.py", line 21, in <module>
    from . import shared
ImportError: cannot import name 'shared' from '__main__' (scripts/test/binaryenjs.py)
```