Fix macos-14 CI error
Previous code errors out with
https://github.com/WebAssembly/binaryen/actions/runs/27311908958/job/80683790417?pr=8829

```console
/Users/runner/work/binaryen/binaryen/src/ir/module-splitting.cpp:855:12: error: reference to local binding 'secondaryUseds' declared in enclosing function 'wasm::ModuleSplitting::(anonymous namespace)::ModuleSplitter::shareImportableItems'
      if ((secondaryUseds[i].*field).contains(name)) {
           ^
/Users/runner/work/binaryen/binaryen/src/ir/module-splitting.cpp:872:26: note: in instantiation of function template specialization 'wasm::ModuleSplitting::(anonymous namespace)::ModuleSplitter::shareImportableItems()::(anonymous class)::operator()<std::unordered_set<wasm::Name>>' requested here
      getUsingSecondaries(memory->name, &UsedNames::memories);
                         ^
/Users/runner/work/binaryen/binaryen/src/ir/module-splitting.cpp:848:22: note: 'secondaryUseds' declared here
  auto [primaryUsed, secondaryUseds] = computeUsedNames();
                     ^
1 error generated.
```

I'm not sure why Mac compiler does not support this, but this fixes the
error. Gemini says the usage of
```cpp
auto [x, y] = ...
```
is fine and used elsewhere in the codebase, but capturing the variable
within a lambda is C++20 P1091R3 feature which Mac doesn't seem to
support yet.